---
- name: creating directory to site
  file:
    path: /var/www/html/{{ site }}
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode:  '0755'
    state: directory

- name: add index to {{ site }}
  ansible.builtin.template:
    src: index.php.j2
    dest: "/var/www/html/{{ site }}/index.php"
    owner: "{{ owner }}"
    group: "{{ group }}"

- name: 'add .conf to {{ site }}'
  ansible.builtin.template:
    src: "{{ site }}.conf.j2"
    dest: "/etc/nginx/conf.d/{{ site }}.conf"
    owner: "{{ owner }}"
    group: "{{ group }}"

- name: restart nginx
  service:
    name: nginx
    state: restarted
