---

- name: Add tomcat group
  group:
    name: tomcat

- name: Add "tomcat" user
  user:
    name: tomcat
    group: tomcat
    home: /opt/tomcat
    createhome: no
    system: yes

- name: Download Tomcat
  get_url:
    url: "{{ tomcat_archive_url }}"
    dest: "{{ tomcat_archive_dest }}"

- name: Create a tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat

- name: Extract tomcat archive
  unarchive:
    src: "{{ tomcat_archive_dest }}"
    dest: /opt/tomcat
    owner: tomcat
    group: tomcat
    remote_src: yes
    extra_opts: "--strip-components=1"
    creates: /opt/tomcat/bin

- name: Copy tomcat service file
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  when: ansible_service_mgr == "systemd"

- name: Start and enable tomcat
  service:
    daemon_reload: yes
    name: tomcat
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"

- name: 'add .conf to {{ site }}'
  ansible.builtin.template:
    src: "{{ site }}.conf.j2"
    dest: "/etc/nginx/conf.d/{{ site }}.conf"

- name: Set UI access credentials
  template:
    src: tomcat-users.xml.j2
    dest: /opt/tomcat/conf/tomcat-users.xml
  notify: restart tomcat

- name: Allow access to Manager and Host Manager apps from any IP
  template:
    src: context.xml.j2 
    dest: "{{ item }}"
  with_items:
    - /opt/tomcat/webapps/host-manager/META-INF/context.xml
    - /opt/tomcat/webapps/manager/META-INF/context.xml
  notify: restart tomcat

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: httpd_can_network_relay
    state: '1'
    persistent: yes

- name: daemon-reload
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes 
    name: crond
    
- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted  

- name: restart nginx
  service:
    name: nginx
    state: restarted